In [ ]:
from lmpy import lme, gam
from lmpy.data import data
from lmpy.compare import anova, AIC, BIC

### 2.5.4 + 2.5.5

In [2]:
Machines = data("Machines", "nlme")
Machines

shape: (54, 3)
┌────────┬─────────┬───────┐
│ Worker ┆ Machine ┆ score │
│ ---    ┆ ---     ┆ ---   │
│ enum   ┆ enum    ┆ f64   │
╞════════╪═════════╪═══════╡
│ 1      ┆ A       ┆ 52.0  │
│ 1      ┆ A       ┆ 52.8  │
│ 1      ┆ A       ┆ 53.1  │
│ 2      ┆ A       ┆ 51.8  │
│ 2      ┆ A       ┆ 52.8  │
│ …      ┆ …       ┆ …     │
│ 5      ┆ C       ┆ 72.0  │
│ 5      ┆ C       ┆ 71.1  │
│ 6      ┆ C       ┆ 62.0  │
│ 6      ┆ C       ┆ 61.4  │
│ 6      ┆ C       ┆ 60.5  │
└────────┴─────────┴───────┘

In [3]:

a1 = lme('score ~ Machine + (1|Worker) + (1|Worker:Machine)', data=Machines)
a2 = lme('score ~ Machine + (1|Worker) + (Machine-1|Worker)', data=Machines)
AIC(a1,a2)

    df     AIC
a1   6  227.69
a2  11  230.31

In [4]:
anova(a1, a2)

refitting model(s) with ML (instead of REML)
Analysis of Variance Table (likelihood ratio test)

a1: score ~ Machine + (1|Worker) + (1|Worker:Machine)
a2: score ~ Machine + (1|Worker) + (Machine-1|Worker)

    npar       AIC       BIC     logLik  deviance   Chisq  Df  Pr(>Chisq)
a1     6  237.2695  249.2034  -112.6347  225.2695
a2    11  238.4185  260.2973  -108.2093  216.4185  8.8509   5      0.1152
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

In [5]:
b1 = gam('score ~ Machine + s(Worker, bs="re") + s(Machine, Worker, bs="re")', data=Machines, method='REML')
b1.vcomp

shape: (3, 4)
┌───────────────────┬──────────┬──────────┬──────────┐
│ name              ┆ std_dev  ┆ lower    ┆ upper    │
│ ---               ┆ ---      ┆ ---      ┆ ---      │
│ str               ┆ f64      ┆ f64      ┆ f64      │
╞═══════════════════╪══════════╪══════════╪══════════╡
│ s(Worker)         ┆ 4.781051 ┆ 2.249858 ┆ 10.15995 │
│ s(Machine,Worker) ┆ 3.729538 ┆ 2.382816 ┆ 5.837404 │
│ scale             ┆ 0.961577 ┆ 0.763254 ┆ 1.211432 │
└───────────────────┴──────────┴──────────┴──────────┘

In [6]:
b2 = gam('score ~ Machine + s(Worker,bs="re") + s(Worker,bs="re",by=Machine)',data=Machines, method='REML')
b2.vcomp

shape: (5, 4)
┌────────────────────┬──────────┬──────────┬───────────┐
│ name               ┆ std_dev  ┆ lower    ┆ upper     │
│ ---                ┆ ---      ┆ ---      ┆ ---       │
│ str                ┆ f64      ┆ f64      ┆ f64       │
╞════════════════════╪══════════╪══════════╪═══════════╡
│ s(Worker)          ┆ 3.785947 ┆ 1.798732 ┆ 7.968613  │
│ s(Worker):MachineA ┆ 1.940322 ┆ 0.253188 ┆ 14.869794 │
│ s(Worker):MachineB ┆ 5.874023 ┆ 2.988334 ┆ 11.546281 │
│ s(Worker):MachineC ┆ 2.84547  ┆ 0.829933 ┆ 9.75585   │
│ scale              ┆ 0.961577 ┆ 0.763254 ┆ 1.211432  │
└────────────────────┴──────────┴──────────┴───────────┘

In [7]:
AIC(b1, b2)

           df     AIC
b1  18.859954  165.19
b2  18.985573  165.62

### 4.6

In [8]:
trees = data("trees", "mgcv")

In [9]:
from lmpy.family import Gamma
ct1 = gam('Volume ~ s(Height) + s(Girth)', family=Gamma(link="log"), data=trees)
ct1.summary()

Family: Gamma
Link function: log

Formula: Volume ~ s(Height) + s(Girth)

Parametric coefficients:
             Estimate  Std. Error  t value  Pr(>|t|)
(Intercept)   3.27570     0.01492    219.6    <2e-16  ***
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
             edf  Ref.df       F   p-value
s(Height)  1.000   1.000   31.32  6.51e-06  ***
s(Girth)   2.422   3.044  219.28   < 2e-16  ***
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) = 0.973  Deviance explained = 97.8%
GCV = 0.0080824  Scale est. = 0.006899  n = 31

In [ ]:
brain = data("gamair","brain")

In [10]:
pisa = data("pisa", "m-clark")
mod_gam1 = gam('Overall ~ s(Income, bs = "cr")', data = pisa)

In [11]:
mod_lm = gam('Overall ~ Income', data = pisa)

In [12]:
mod_lm.summary()

Family: gaussian
Link function: identity

Formula: Overall ~ Income

Parametric coefficients:
             Estimate  Std. Error  t value  Pr(>|t|)
(Intercept)    204.32       35.37    5.777  4.32e-07  ***
Income         355.85       46.79    7.606  5.36e-10  ***
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) = 0.518  Deviance explained = 52.7%
GCV = nan  Scale est. = 1448.8  n = 54

In [13]:
mod_gam1 = gam('Overall ~ s(Income, bs = "cr")', data = pisa)

In [14]:
mod_gam1.summary()

Family: gaussian
Link function: identity

Formula: Overall ~ s(Income, bs = "cr")

Parametric coefficients:
             Estimate  Std. Error  t value  Pr(>|t|)
(Intercept)   470.444       4.082    115.3    <2e-16  ***
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
             edf  Ref.df      F   p-value
s(Income)  6.895   7.741  16.67  3.80e-11  ***
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) = 0.7  Deviance explained = 73.9%
GCV = 1053.7  Scale est. = 899.67  n = 54